In [1]:
import numpy as np 
from scipy.integrate import odeint
import os, sys 
from pathlib import Path
from os.path import dirname, realpath
script_dir = Path(dirname(realpath('.')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
import utility as ut
import sample as sm
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
L63_data_folder = '../data/L63-trajectories'
u = np.load('{}/validation.npy'.format(L63_data_folder))
rs = sm.MatrixSampler(0.4, 3.5, u.T)
n_rows = [200, 50, 50] 
n_sample = 2048
rows, bs = rs.sample(n_rows, n_sample)
print(rows.shape, bs.shape)
rows, bs = rs.sample_parallel(n_rows, n_sample)
print(rows.shape, bs.shape)
rows, bs = rs.sample_parallel_3(n_rows, n_sample)
print(rows.shape, bs.shape)

Time taken by sample is 29.8558030128479 seconds
(2048, 300, 3) (2048, 300)
Time taken by sample_parallel is 7.632298946380615 seconds
(2048, 300, 3) (2048, 300)
Time taken by sample_parallel_3 is 16.06141686439514 seconds
(2048, 300, 3) (2048, 300)


In [3]:
# for i in range(50):
#     rows, bs = rs.sample(300)
#     print(rs.test_rows(rows, bs).sum())

In [4]:
res = []
for _ in range(10000):
    ratio = np.random.randint(low=1, high=3, size=3).astype(float)
    ratio /= ratio.sum()
    n_rows = 300
    res.append((n_rows * ratio).astype(int).sum() == n_rows)
np.array(res).sum()

10000

In [5]:
rows.shape

(500, 300, 3)

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
ms = sm.MatrixSampler(0.4, 3.5, u.T)
m, b = ms.sample_([200, 50, 50])

In [8]:
n = 10
dx = 100./10.
l = np.arange(0., 100. + dx, dx)
d = ((100. + dx - l) / dx).astype(int)

In [9]:
l, d

(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1]))

In [10]:
len()

TypeError: len() takes exactly one argument (0 given)

In [ ]:
def get_row_partitions(n_rows):
    i = np.random.randint(len(l))
    good = int(l[i]* n_rows / 100.)
    j = np.random.randint(d[i])
    linear = int(l[j]* n_rows / 100.)
    extreme = n_rows - good - linear
    return [good, linear, extreme]

In [ ]:
for _ in range(50):
    print(get_row_partitions(300))

In [ ]:
(6 * 12 / 2) * 500

In [ ]:
!pip install joblib

In [ ]:
np.hstack([1., 3., 4.])

In [ ]:
g = lambda x: np.linalg.norm(x)

In [ ]:
rs = sm.GoodRowSampler(0.4, 3.5, u.T)
rows, bs = rs.sample(300)

In [ ]:
rows.shape, bs.shape

In [4]:
a = 4.5657
b = 5.6768
print(f'{b-a:.2f}')

1.11
