In [1]:
import numpy as np 
from scipy.integrate import odeint
import os, sys, warnings
from pathlib import Path
from os.path import dirname, realpath
script_dir = Path(dirname(realpath('.')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
import utility as ut
import surrogate_nn as srnn
import matplotlib.pyplot as plt
import pandas as pd
import torch
from torch import nn
from torch.optim import lr_scheduler
from torch.utils.data import DataLoader, TensorDataset, RandomSampler
warnings.filterwarnings('ignore')

In [2]:
L63_data_path = '../data/L63-trajectories'
N = 20
train = np.load(f'{L63_data_path}/train.npy')[:, :N].astype(np.float32)
train_dataset = TensorDataset(torch.Tensor(train[:, :-1].T), torch.Tensor(train[:, 1:].T))
train_dataloader = DataLoader(train_dataset, batch_size=int(N/10))#, shuffle=True)

In [14]:
for i, batch in enumerate(DataLoader(train_dataset, batch_size=1)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [22]:
sampler = RandomSampler(train_dataset, replacement=True, num_samples=int(1e100))
dataloader = DataLoader(train_dataset, sampler=sampler, batch_size=2)
k = 0
while k < 50:
    x, y = next(dataloader.__iter__())
    print(x)
    k += 1

tensor([[-12.4832, -16.9737,  26.6290],
        [ -8.3611, -13.3140,  18.1467]])
tensor([[ -9.5421,  -2.8141,  35.0067],
        [-10.8660,  -4.4440,  36.1698]])
tensor([[-13.2750, -16.6191,  29.4810],
        [ -9.3860, -14.6547,  19.6255]])
tensor([[-13.7892, -15.5165,  32.2080],
        [-10.4542, -15.8231,  21.5584]])
tensor([[-10.8660,  -4.4440,  36.1698],
        [ -8.3611, -13.3140,  18.1467]])
tensor([[-11.5119, -16.6562,  23.9250],
        [ -4.8146,  -0.2847,  28.8859]])
tensor([[-13.7892, -15.5165,  32.2080],
        [ -6.9417,  -0.8950,  32.0093]])
tensor([[-13.9434, -13.7203,  34.5039],
        [-13.7892, -15.5165,  32.2080]])
tensor([[-13.2750, -16.6191,  29.4810],
        [-13.2750, -16.6191,  29.4810]])
tensor([[-12.0731,  -6.5216,  36.8642],
        [-10.4542, -15.8231,  21.5584]])
tensor([[-13.6936, -11.4263,  36.1102],
        [-13.2750, -16.6191,  29.4810]])
tensor([[ -5.8015,  -0.4695,  30.4289],
        [ -8.3611, -13.3140,  18.1467]])
tensor([[-10.4542, -15.8231,